spring.application.name=product-service

server.port=8082


# --------------------------
# DATABASE (MongoDB)
# --------------------------
# Format: mongodb://user:pass@host:port/dbname?authSource=admin
spring.mongodb.uri=mongodb://admin:password@localhost:27017/product_db?authSource=admin

# --------------------------
# ACTUATOR
# --------------------------
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=when-authorized